### ISSUE TITLE
Host on github pages

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-website#1]
Heroku is overkill for doc site. Let host it on github pages.

**Comment by christianalfoni** [comment]
I disagree :-) Everybody hosts on github pages. We can do some pretty cool things hosting it ourselves and especially now that it is running with Cerebral. We can do some recording maybe and I really want to use the web page as an example of universal Cerebral app. It has a really good scope for it :)

**Comment by Guria** [comment]
@christianalfoni `universal` is good point. Agreed
