### ISSUE TITLE
update testing documentation

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-website#13]
Check and update [testing documentation](http://www.cerebraljs.com/testing) with latest changes.
At least it contains old action signature.
PR are welcome.

**Comment by Guria** [comment]
Also would be great to review best practicies section.

**Comment by Guria** [comment]
still used deprecated methods, eg. `Controller(model, services)`

**Comment by Guria** [comment]
@christianalfoni we need document `cerebral-testable` and `connect`/`Computed` behaviour with NODE_ENV='test'

**Comment by garth** [comment]
done
