### ISSUE TITLE
Meaningfull urls

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-website#2]
Now http://www.cerebraljs.com/#/6/1:
- link doesn't say where it would lead
- could lead in other place after rearranging in menu

After http://www.cerebraljs.com/#/signals/input
- link say where it would lead
- would lead to the same place even after rearranging in menu

**Comment by christianalfoni** [comment]
Yup, completely agree here. It was a bad choice. Will change this :)

**Comment by christianalfoni** [comment]
Fixed now :-)
