### ISSUE TITLE
glitchy scroll on menu

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-website#3]
Both http://www.christianalfoni.com/cerebral/  and http://www.cerebraljs.com/ has glitchy scroll in menu.

**Comment by rrag** [comment]
+1 
reset the scroll on menu change. It gets irritating to scroll back to top every time I change the left nav. Also scroll bar is not visible, it is because of the 

``` css
.page {
    height: 100%;
}
```

but removing that makes the whole left nav also scroll, I can figure out a fix and PR it if you don't already have it addressed.

**Comment by Guria** [comment]
Haven't touched it yet. Pr are welcome

**Comment by christianalfoni** [comment]
I fixed the scrolling back to top thingy :-) Not sure what glitchy is referring to?

**Comment by christianalfoni** [comment]
Closing it for now :-)

**Comment by Guria** [comment]
But it still glitchy :)

**Comment by Guria** [comment]
I mean scroolbar in sidebar nav. Scrollbar is present but it overflows down under the screen edge (only top arrow seen, scrollbar disabled if it nothing to scroll). Good news is mousewheel scrolling still scrolls sidebar container.

**Comment by christianalfoni** [comment]
Hehe, I am on a mac, can not see the scrollbar :p

**Comment by christianalfoni** [comment]
Need help to fix this one :-)

**Comment by Guria** [comment]
thanks @NervosaX

**Comment by NervosaX** [comment]
Very happy to fix this, it was bothering me a lot.
