### ISSUE TITLE
type error in markdown/nesting.md

### ISSUE THREAD

**Issue by henri-hulski** [cerebral/cerebral-website#31]
> // We just add the chains that puts the application in
>    // "messagesOpened" state
>    messageOpened: [...messagesOpened, ...messageOpened]

and 

> When the user goes to **/messages/123** the **messagesOpened** and **messageOpened** chain will run.

looks a little strange to me.

At least it's hard to reason about  ;)

**Comment by Guria** [comment]
Could you clarify more? What exactly here is issue? Does it about [array spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)?

**Comment by henri-hulski** [comment]
It was about 3 times using `messageOpened`. 
But maybe I just don't understand it.

**Comment by henri-hulski** [comment]
Ok, I read it another time and actually it's `messageOpened` and `messagesOpened`. This makes somehow sense. 
So sorry for this.

**Comment by christianalfoni** [comment]
Though you make a good point @henri-hulski , we should change it to avoid confusion. Very easy to misread that
