### ISSUE TITLE
Show folder structure to new users

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral-website#43]
To me it's always very helpful to look a frameworks recommended folder structure before reading about whats what. It's an easy way to get  an overview of the bits an pieces. When you then later read about them you will already know where it sits in your project :)

Hope this makes sense - I had a bear or two before I took this note.

**Comment by Guria** [comment]
http://www.cerebraljs.com/documentation/structuring_your_project
is it ok?

**Comment by maxfrigge** [comment]
LGTM 👍
