### ISSUE TITLE
Mention perfomance in Choosing a model

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral-website#47]
Not even sure how big the performance gain is, but in theory the rendering performance should be better when using immutable model in combination with shouldComponentUpdate and shallow checking.

**Comment by edgesoft** [comment]
@maxfrigge The set or merge of large datasets is slower on immutable then mutable. shouldComponentUpdate always returns false with the new cerebral-view-react.  So I don't think you need to do the checking.

**Comment by maxfrigge** [comment]
@edgesoft I agree that the performance of expensive state mutations will increase without immutable state, but afaik Cerebral will only be able to efficiently update the views that are directly connected to the state using `connect` all sub components are most likely being re rendered each time, whether their data changed or not.

**Comment by edgesoft** [comment]
+1

**Comment by Guria** [comment]
@maxfrigge @edgesoft mutable model now has "Improved performance on large datasets" point in doc. is it enough?

**Comment by edgesoft** [comment]
@Guria Yes!

**Comment by maxfrigge** [comment]
@Guria Should do it for now. There is also the other side where your view's performance could be optimised with immutable data, but I don't think that it the impact will be big enough to actually care :)  .. and it seems that nobody really researched this further.
